name: bert-squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ujson
  - numpy
  - pip
  - spacy
  - tensorboard
  - tqdm
  - urllib3
  - pytorch
  - jupyter
  - ipykernel
  - pip:
    - torch
    - docopt